#!/usr/bin/env bash

s="dave gray"

echo "$s"

echo "${s}"

#length
echo "${#s}"

#capitalize first char
echo "${s^}"

#capitalize all letters
echo "${s^^}"

#capitalize all a
echo "${s^^a}"

#${s^a} will result in Apple, but ${s^p} will result in apple because the first letter is not a p
echo "${s^r}"

#capitalize d and a
echo "${s^^[ad]}"

s='DAVE EDDY'

echo "${s,}" #first char to lowercase
echo "${s,,}" #all to lower case

echo "${s,,D}"

echo "${s,,[DA]}"